version: '3'

services:
  mysql:
    image: mysql
    restart: always
    ports:
      - '${DB_PORT}:${DB_PORT}'
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
    env_file:
      - .env
